apiVersion: v1
kind: Service
metadata:
  name: docs-8-service
spec:
  selector:
    app: docs-8
  ports:
    - protocol: TCP
      port: 8080 ## service暴露的端口
      targetPort: 80 ## 容器的短裤
      nodePort: 32215 ## 指定访问的端口
  type: NodePort
